# Assignment 4: Numpy

January 1, 2019

**Jane Programmer**

As usual, we're just offering some scaffolding here, not the entire completed code.  Feel free to use your own ingenuity to come up with a different approach.

We begin by importing the packages and modules we need, and then getting our data loaded. We use `genfromtxt` to get data from a CSV into a numpy array called `water_use`.  We'll want to specify our delimiter (a comma) and that we want to skip the header.

In [1]:
import numpy as np
from numpy import genfromtxt

water_use = genfromtxt(# do some stuff here)

Let's check the type of `water_use`, then view it.

In [2]:
type(water_use)

numpy.ndarray

In [3]:
water_use

array([[1.9790000e+03, 7.1021000e+06, 1.5120000e+03, 2.1300000e+02],
       [1.9800000e+03, 7.0716390e+06, 1.5060000e+03, 2.1300000e+02],
       [1.9810000e+03, 7.0892410e+06, 1.3090000e+03, 1.8500000e+02],
       [1.9820000e+03, 7.1091050e+06, 1.3820000e+03, 1.9400000e+02],
       [1.9830000e+03, 7.1812240e+06, 1.4240000e+03, 1.9800000e+02],
       [1.9840000e+03, 7.2345140e+06, 1.4650000e+03, 2.0300000e+02],
       [1.9850000e+03, 7.2740540e+06, 1.3260000e+03, 1.8200000e+02],
       [1.9860000e+03, 7.3192460e+06, 1.3510000e+03, 1.8500000e+02],
       [1.9870000e+03, 7.3424760e+06, 1.4470000e+03, 1.9700000e+02],
       [1.9880000e+03, 7.3537190e+06, 1.4840000e+03, 2.0200000e+02],
       [1.9890000e+03, 7.3441750e+06, 1.4020000e+03, 1.9100000e+02],
       [1.9900000e+03, 7.3356500e+06, 1.4240000e+03, 1.9400000e+02],
       [1.9910000e+03, 7.3745010e+06, 1.4690000e+03, 1.9900000e+02],
       [1.9920000e+03, 7.4289440e+06, 1.3690000e+03, 1.8400000e+02],
       [1.9930000e+03, 7.5061660e+

Change numpy's print options to suppress scientific notation and try viewing the data again!

In [4]:
np.set_printoptions(# what might help?)
water_use

array([[   1979. , 7102100. ,    1512. ,     213. ],
       [   1980. , 7071639. ,    1506. ,     213. ],
       [   1981. , 7089241. ,    1309. ,     185. ],
       [   1982. , 7109105. ,    1382. ,     194. ],
       [   1983. , 7181224. ,    1424. ,     198. ],
       [   1984. , 7234514. ,    1465. ,     203. ],
       [   1985. , 7274054. ,    1326. ,     182. ],
       [   1986. , 7319246. ,    1351. ,     185. ],
       [   1987. , 7342476. ,    1447. ,     197. ],
       [   1988. , 7353719. ,    1484. ,     202. ],
       [   1989. , 7344175. ,    1402. ,     191. ],
       [   1990. , 7335650. ,    1424. ,     194. ],
       [   1991. , 7374501. ,    1469. ,     199. ],
       [   1992. , 7428944. ,    1369. ,     184. ],
       [   1993. , 7506166. ,    1368.5,     182. ],
       [   1994. , 7570458. ,    1357.7,     179. ],
       [   1995. , 7633040. ,    1325.7,     174. ],
       [   1996. , 7697812. ,    1297.9,     169. ],
       [   1997. , 7773443. ,    1205.5,     1

What do each of the columns represent?  Go back to the web page where you found this data, if needed.

* Col 1 = ??
* Col 2 = ??
* Col 3 = ??
* Col 4 = ??

Answer the following questions, using numpy slicing and operations:

* What is the maximum yearly NYC consumption in millions of gallons per day?

In [5]:
water_use# some code here

1512.0

* How many years are represented in this data?  Try using numpy's `shape` command.

In [6]:
water_use.shape

(39, 4)

* What is the mean and the standard deviation of the per capity daily water consumption?

In [7]:
water_use#some code here

160.30769230769232

In [8]:
water_use#some code here

31.51894330370624

* What is the increase or decrease in population from year to year?  Use numpy's `diff` function to create an array of differences and save that to the variable "pop_diff", then print that variable.

In [9]:
pop_diff = np.diff#some code here
pop_diff

array([-30461. ,  17602. ,  19864. ,  72119. ,  53290. ,  39540. ,
        45192. ,  23230. ,  11243. ,  -9544. ,  -8525. ,  38851. ,
        54443. ,  77222. ,  64292. ,  62582. ,  64772. ,  75631. ,
        84816. ,  89401. ,  60618. ,  16685.5,  16685.5,  16685.5,
        16685.5,  16685.5,  16685.5,  16685.5,  16685.5,  16685.5,
        16685.5, 108965. ,  77081. ,  61281. ,  49530. ,  44512. ,
        21171. ,  85025. ])

* What's the python type (use `type`) of pop_diff?

In [10]:
type(pop_diff)

numpy.ndarray

* What's the numpy datatype (use numpy's `dtype`) of pop_diff?

In [11]:
pop_diff.dtype

dtype('float64')

* How many elements are in `pop_diff`?  Why is that different from the number of rows in our 2D array?

In [12]:
pop_diff.size

38

There are 39 ***years*** but only 38 ***differences***, because ...

Now that we know the mean and standard deviation of the average per-capity daily water use  over this time period, we can create a simulation of per capita daily water use over this time frame.  Take the number of years, multiply by 365.25, and round to the nearest whole integer.  That's the number of values we want to generate.  

Then, using numpy's `random` package, create an array that contains that number of values, normally distributed, with the mean and standard deviation you figured out for per capita daily water use.  Save that array to `simulated_daily_use_array`.

Hint: use `help(np.random.normal)` to get some info that will help you!

In [13]:
num_values = round(39*365.25)

In [14]:
simulated_daily_use_array = np.random.normal(# add a mean, standard deviation, and number of values)

Now, check that `simulated_daily_use_array` is actually a numpy array, and create a list that has the exact same values, but isn't an array, but rather a list.  Call it `simulated_daily_use_list`.

In [15]:
type(simulated_daily_use_array)

numpy.ndarray

In [16]:
simulated_daily_use_list = list(simulated_daily_use_array)

In [17]:
type(simulated_daily_use_list)

list

Now we're going to do some profiling of performance.  We will use three different methods to find the square root of each simulated water use, and we'll use `timeit` to figure out what is quickest.  Let's say we had to do this for the water use over 39 years for 1000 New Yorkers!

In [18]:
from timeit import timeit
import math

def sqrt_1():
    # This one uses a loop.  Slow!
    sqrt_1 = [] 
    for i in range(0, len(simulated_daily_use_list)-1):  
        sqrt_1.append(math.sqrt(simulated_daily_use_list[i]))
    return(sqrt_1)

def sqrt_2():
    # This one uses list comprehension. Better!
    return([math.sqrt(x) for x in simulated_daily_use_list])

def sqrt_3():
    # This one uses numpy.  Best!
    return(np.sqrt(simulated_daily_use_array))

print("Time for loop: " + str(timeit(sqrt_1, number = 1000)))
print("Time for list comprehension: " + str(timeit(sqrt_2, number = 1000)))
print("Time for numpy vectorized operation: " + str(timeit(sqrt_3, number = 1000)))

Time for loop: 2.502703570993617
Time for list comprehension: 1.314091111999005
Time for numpy vectorized operation: 0.06584935099817812
